services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dokobit_task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  dokobit-task:
    depends_on:
      - db
    image: dokobit-task
    build:
      context: .
    container_name: dokobit-task
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8080
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB_URL: 'postgresql://db:5432/dokobit_task'